CREATE DATABASE IF NOT EXISTS PHPshop;

CREATE TABLE IF NOT EXISTS types (
    ID INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(45) NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_title(Title),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS categories (
    ID INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(45) NOT NULL,
    Image VARCHAR(255),
    TypeID INT NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_title(Title),
    PRIMARY KEY (ID),
    FOREIGN KEY (TypeID) REFERENCES types(ID)
);

CREATE TABLE IF NOT EXISTS subcategories (
    ID INT NOT NULL AUTO_INCREMENT,
    CategoryID INT NOT NULL,
    Title VARCHAR(45) NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_title_per_category(Title, CategoryID),
    PRIMARY KEY (ID),
    FOREIGN KEY (CategoryID) REFERENCES categories(ID)
);

CREATE TABLE IF NOT EXISTS items (
    ID INT NOT NULL AUTO_INCREMENT,
    SubcategoryID INT NOT NULL,
    Title VARCHAR(45) NOT NULL,
    Image VARCHAR(255),
    Price DOUBLE NOT NULL,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ChangeDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (SubcategoryID) REFERENCES subcategories(ID)
);
